name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        cache: true

    - name: Install dependencies
      run: make deps

    - name: Run tests
      run: make test

    - name: Build release binaries
      run: make release

    - name: Generate changelog
      id: changelog
      run: |
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body: |
          ## Changes in this Release
          ${{ env.CHANGELOG }}
          
          ## Installation
          
          Download the appropriate binary for your platform and make it executable:
          
          ```bash
          chmod +x certgen-*
          ./certgen --help
          ```
        files: |
          certgen-*
          checksums.txt
        fail_on_unmatched_files: true
        generate_release_notes: true